### ISSUE TITLE
get_users() Not Populating All Data

### ISSUE THREAD

**Issue by commitconfirm** [levensailor/ciscoaxl#13]
Might have a bug here. I was recently pulling data from CUCM with `get_users()` and noticed that there were a bunch of fields not populating data. Several keys were missing values.

Keys I can see missing data:

- mailid
- primaryExtension
- telephoneNumber
- enableMobility

I can verify this by checking the userid with `get_user(userid='xxxxxx')`, which does show all the data.

Not a huge issue because I can get around this via other means, but it seems like most of the attributes have `None` values.  

Is there something I'm missing here? These are local accounts on CUCM.

**Comment by commitconfirm** [comment]
Been doing some research and testing, and I think I've figured some things out, but I'm also a little confused. If I run `get_users()` I get the following:

```
    'firstName': None,
    'middleName': None,
    'lastName': 'This is a Last Name',
    'emMaxLoginTime': None,
    'userid': '1111111',
    'mailid': None,
    'department': None,
    'manager': None,
    'userLocale': None,
    'primaryExtension': None,
    'associatedPc': None,
    'enableCti': None,
    'subscribeCallingSearchSpaceName': None,
    'enableMobility': None,
    'enableMobileVoiceAccess': None,
    'maxDeskPickupWaitTime': None,
    'remoteDestinationLimit': None,
    'status': None,
    'enableEmcc': None,
    'patternPrecedence': None,
    'numericUserId': None,
    'mlppPassword': None,
    'homeCluster': None,
    'imAndPresenceEnable': None,
    'serviceProfile': None,
    'directoryUri': None,
    'telephoneNumber': None,
    'title': None,
    'mobileNumber': None,
    'homeNumber': None,
    'pagerNumber': None,
    'calendarPresence': None,
    'userIdentity': None,
    'uuid': '{xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx}'
```

First and last names are filled along with userID and uuid. I find this odd that it's display this info, but none of the other key have values in them (they have `None` values). 

Now reading the [pypi page](https://pypi.org/project/ciscoaxl/), it mentions you can allow more fields to be returned. So I added tagfilters to `get_users()` like so:

```
    tf = {'tagfilter': {
        'telephoneNumber': '',
        'mailid': '',
        'primaryExtension': '',
        'enableMobility': '',
        'firstName': '',
        'lastName': '',
        'userid': ''
        }
    }
    print(ucm.get_users(**tf))
```

Then the fields I'm looking for populate. Seems to be solved then, but I'm confused as to why the default `get_users()` dictionary displays keys with no values. Is this the expected behavior?

I'm hesitant to call it resolved, but seems like I've found the solution for now.

**Comment by bradh11** [comment]
This is the current as designed behavior, but I am curious what others think should be expected here.  The original implementation did not return all fields for performance reasons - however in my testing I could not validate there was any noticeable impact.  At the time the tagfilter option wasn’t exposed in the library.  I created a PR to add it a while back.  

At the very least we can better document the tagfilter feature n the documentation.  

I’m open to suggestions.

**Comment by commitconfirm** [comment]
Thanks for the prompt reply! 

In my opinion, I think if `get_users()` (or any method) has a limited set of default values its pulling, only those key-values should be returned otherwise the user may think the values don't exist, there's a bug (especially when working with Cisco code), or some other error or problem is occurring. 

That said, the easiest solution for now is, like you said, just updating the documentation to indicate that `get_users()` only pulls certain values and the rest that appear in the returned dictionary are just placeholders for additional values you could also pull with `tagfilter=`. 

Thanks again for the reply. I'll go ahead and close this issue as* it's working as designed.

**Comment by Letshadow** [comment]
I tried to get the routePartitionName from the primaryExtension in EndUser but it always shows None
`ucm.get_users(tagfilter={'userid':'','primaryExtension':''})`

```
'primaryExtension': {
          'pattern': '1802',
          'routePartitionName': None
      },
```
EndUsers can have DirectoryNumbers in different partitions

![image](https://user-images.githubusercontent.com/44853747/173220841-721b7cd5-e6fc-4505-8573-5d4e7b2f588b.png)

There is no way to always check a correct configuration
Reasons:
In the DirectoryNumbers there is no longer a specific mandatory field for the EndUser.
One way would be to get the Enduser from the directoryURIs but this field is optional in the form.
you can get the associatedDevices in the DirectoryNumber and then check that EndUser is in the ownerUserName but this field is not required and an anonymous ownerUser can be used
Therefore, the partitions are essential.
