### ISSUE TITLE
get_directory_number() return missing ["return"]["line"]

### ISSUE THREAD

**Issue by rlad78** [levensailor/ciscoaxl#18]
This is a bit of a nitpick, but it's something that gave me quite a headscratch. When trying to pull some details from a DN, I noticed that the returned object had an attribute of `return`. I had been diving into other objects' info using their attributes (didn't know I could just access zeep's objects using dict notation), so I was confused how I was going to get into the DN data like this...

```python
dn = ucm.get_directory_number(pattern='5550001', routePartitionName='my-partition')
print(dn.return.line.associatedDevices.device)
```

Needless to say, Python didn't like me using the reserved word `return` to try and access an attribute.

Is there any way this method's return can get the same treatment as something like get_phone()?

https://github.com/PresidioCode/ciscoaxl/blob/d5a40cca2bc829b7d7d78180185c127cd302c0e6/ciscoaxl/axl.py#L1909-L1918

**Comment by mabildg30** [comment]
Same issue on get_route_list. 
Have edited the axl.py file and added ["return"]["routeList"] on my local install.

**Comment by bradh11** [comment]
will work to standardize all of the returns - this makes good sense

**Comment by bradh11** [comment]
get_directory_numbers has been corrected a while ago, but to the greater point we need to standardize the returns.  closing this specific issue out, but will keep the umbrella issue
