### ISSUE TITLE
Remote Destination

### ISSUE THREAD

**Issue by Sivolen** [levensailor/ciscoaxl#19]
Hi!
Help me please, how i make a new remote destination profile, i using version 10.5? 
In documentations i don't find this

**Comment by rlad78** [comment]
My current computer doesn't have access to my UCM cluster, so I wasn't able to test this. This is the general layout though for all required values.
```py
axl_obj.client.addRemoteDestination(remoteDestinationProfile={
    "name": "test",
    "product": "Cisco 8845",
    "class": "Phone",
    "protocol": "SIP",
    "protocolSide": "User",
    "devicePoolName": "Device Pool",
    "lines": {
        "line": [
            {
                "index": 1,
                "dirn": {
                    "pattern": "5556669999",
                    "routePartitionName": "Default-PT"
                },
                "display": "John Doe",
                "displayAscii": "John Doe",
                "label": "John Doe - 9999",
                "e164Mask": "5556669999",
            }
        ]
    },
    "callInfoPrivacyStatus": "Default",
    "userId": "jdoe",
})
```
The rest of the accepted values can be found using the [AXL Schema Reference](https://developer.cisco.com/docs/axl-schema-reference/) (CTRL +F and search for "addRemoteDestinationReq").

**Comment by Sivolen** [comment]
Hm, Thanks
But i have a question 

```
i tried run this code 


remote_destination = {

"name": "Gridnev.A.A._RDI",
"destination": "mynumber",
"ownerUserId": "a.gridnev",
"enableUnifiedMobility": "true",
"enableMobileConnect": "true",
"isMobilePhone": "true",
"remoteDestinationProfileName": "Gridnev.A.A._RDPI",
# "lineAssociations": "1"
}

# service.addRemoteDestination(remoteDestination=remote_destination)

node = client.create_message(service, 'addRemoteDestination', remoteDestination=remote_destination)

# Remove the dualModeDeviceName element
for element in node.xpath("//dualModeDeviceName"):
    element.getparent().remove(element)

    resp = transport.post_xml('https://10.40.1.11:8443/axl/',
    envelope=node,
    headers=None
)


```
If i uncomment # "lineAssociations": "1" this code not work and if i comment it then script work korrect but i don't understand how enable add line in my profile?

**Comment by Sivolen** [comment]
I changed the dict and it works fine 
remote_destination = {

    "name": "Gridnev.A.A._RDI",
    "destination": "number",
    "ownerUserId": "a.gridnev",
    "enableUnifiedMobility": "true",
    "enableMobileConnect": "true",
    "isMobilePhone": "true",
    "remoteDestinationProfileName": "Gridnev.A.A._RDPI",
    "lineAssociations": {
        "lineAssociation": [
            {
                "pattern": "number",
                "routePartitionName": "Internal",
            }
        ]
    }
