### ISSUE TITLE
ucm.get_directory_number() not working

### ISSUE THREAD

**Issue by rschuknecht** [levensailor/ciscoaxl#3]
When i try to use ucm.get_directory_number(directory_number='555666', partition='some-pt')
i get a TypeError: {http://www.cisco.com/AXL/API/11.5}GetLineReq() got an unexpected keyword argument 'partition'. Signature: `({uuid: {http://www.cisco.com/AXL/API11.5}XUUID} |{pattern: xsd:string, routePartitionName: {http://www.cisco.com/AXL/API/11.5}XFkType}), returnedTags: {http://www.cisco.com/AXL/API/11.5}Rline, sequence: xsd:unsignedLong'

**Comment by QJarhead** [comment]
Hey @rschuknecht ,

you have to use "routePartitionName" instead of "partition".

I have created a pull request: #5
