### ISSUE TITLE
get_users() Not Populating All Data (routePartitionName from primaryExtension)

### ISSUE THREAD

**Issue by Letshadow** [levensailor/ciscoaxl#31]
I tried to get the routePartitionName from the primaryExtension in EndUser but it always shows None
`ucm.get_users(tagfilter={'userid':'','primaryExtension':''})`

```
'primaryExtension': {
          'pattern': '1802',
          'routePartitionName': None
      },
```
EndUsers can have DirectoryNumbers in different partitions

![image](https://user-images.githubusercontent.com/44853747/173220841-721b7cd5-e6fc-4505-8573-5d4e7b2f588b.png)

There is no way to always check a correct configuration
Reasons:
In the DirectoryNumbers there is no longer a specific mandatory field for the EndUser.
One way would be to get the Enduser from the directoryURIs but this field is optional in the form.
you can get the associatedDevices in the DirectoryNumber and then check that EndUser is in the ownerUserName but this field is not required and an anonymous ownerUser can be used
Therefore, the partitions are essential.

_Originally posted by @Letshadow in https://github.com/levensailor/ciscoaxl/issues/13#issuecomment-1153086816_

**Comment by rlad78** [comment]
This is due to the way AXL handles returnedTags aka what `tagfilter` supplies to. Nested values are mostly ignored unless you provide the child tags specifically.

To resolve your issue, you'd need to change `tagfilter` to `{'userid':'', 'primaryExtension': {'pattern':'', 'routePartitionName': ''}}`. You should see a result like this:
```
    'primaryExtension': {
        'pattern': '5550001',
        'routePartitionName': 'Phones-PT'
    },
```

We have a way of resolving this with PR #30 where supplying a tag will automatically add all relative child tags, but it'll be awhile before it gets implemented into a release.

**Comment by Letshadow** [comment]
perfect thank you very much for your prompt response, in my opinion not taking all the relative child tags can give a more precise filter and help a little with the processing speed effectively since for meters as in the devices they have many relative child tags
```
'lines': {
        'line': [
            {
                'index': 1,
                'label': None,
                'display':None,
                'dirn': {
                    'pattern': '1802',
                    'routePartitionName': {
                        '_value_1': 'Cu45-DirNum-PT',
                        'uuid': '{74FD8173-0DF0-BB0C-234D-E0D6CFD9D0A5}'
                    },
                    'uuid': '{F11B7EAD-A98E-8638-1B7B-8E84CB936A72}'
                },
                'ringSetting': 'Use System Default',
                'consecutiveRingSetting': 'Use System Default',
                'ringSettingIdlePickupAlert': 'Use System Default',
                'ringSettingActivePickupAlert': 'Use System Default',
                'displayAscii': None,
                'e164Mask': '+5717480000',
                'dialPlanWizardId': None,
                'mwlPolicy': 'Use System Policy',
                'maxNumCalls': 4,
                'busyTrigger': 2,
                'callInfoDisplay': {
                    'callerName': 'false',
                    'callerNumber': 'false',
                    'redirectedNumber': 'false',
                    'dialedNumber': 'false'
                },
                'recordingProfileName': {
                    '_value_1': None,
                    'uuid': None
                },
                'monitoringCssName': {
                    '_value_1': None,
                    'uuid': None
                },
                'recordingFlag': 'Call Recording Disabled',
                'audibleMwi': 'Default',
                'speedDial':None,
                'partitionUsage': 'General',
                'associatedEndusers': {
                    'end user': [
                        {
                            'userId': 'user18'
                        }
                    ]
                },
                'missedCallLogging': 'true',
                'recordingMediaSource': 'Gateway Preferred',
                'ctiid': None,
                'uuid': '{9192C6D3-F2E7-060F-983C-965727D74006}'
            }
        ],
        'lineIdentifier': None
    },
```
I'm glad they remove the default none from non-filtered fields :)
, maybe since the dictionaries are without values ​​add a value in the Dupla in the filter tag that allows you to select this behavior if you want all the children or specify them
being by default the current behavior
```
{'userid':'', 'primaryExtension': 'all'}
{'userid':'', 'primaryExtension': {'pattern':''}}
```

On the other hand, also enable the other fields with a simple notice that may take longer to process and not deny access, since the power of the machines may be very relative.

**Comment by rlad78** [comment]
> perfect thank you very much for your prompt response, in my opinion not taking all the relative child tags can give a more precise filter and help a little with the processing speed effectively since for meters as in the devices they have many relative child tags

This is something I want to do in the future, the logic for it is just a bit more difficult for nested dicts. Definitely possible though 👍
