### ISSUE TITLE
README: replace directory_number with pattern

### ISSUE THREAD

**Issue by romanstech** [levensailor/ciscoaxl#47]
Link: https://github.com/levensailor/ciscoaxl#get-specific-directory-number.
Need to replace argument name from **directory_number** to **pattern**.
My system:

> Cisco Unified CM Administration
> System version: 12.5.1.12900-115

Code must be:
```
dn = ucm.get_directory_number(pattern='2888',routePartitionName='losfeliz-pt')
print(dn.uuid)
```

**Comment by bradh11** [comment]
opening a PR for this now...

**Comment by bradh11** [comment]
This is fixed in PR https://github.com/levensailor/ciscoaxl/pull/60
