### ISSUE TITLE
SSL verification disabled

### ISSUE THREAD

**Issue by Insigna2020** [levensailor/ciscoaxl#8]
Hi, 

You have SSL verification disabled and you are suppressing the warnings.  It would be nice if it SSL verification would be part of initializing the class. That way one can choose to enable and provide the path for the certificate.

**Comment by rlad78** [comment]
As of #27, you can now set `strict_ssl=True` when creating a new `axl` instance to enforce SSL verification:

https://github.com/levensailor/ciscoaxl/blob/5cae8eb3de6c622b26f25b36c59ec29095541d1a/ciscoaxl/axl.py#L29-L42
